title: Paper Summaries
markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: "posts"  
      type: "pages"
    values:
      layout: default 

include:
  - posts